trans = {
	'en': {
	# сообщение о блоках
		'<b>Отлично! Теперь вам доступно несколько блоков для изучения.</b> (Вы всегда сможете вернуться к этому сообщению, используя команду /blocks. Что бы поменять язык, используйте /lang):\n\n\n🍾<b>Культура и тенденции.</b>\nУзнайте, что популярно сейчас: музыка, кино, искусство, развлечения и другие активности: рекомендации мест по категориям.\n\n👾<b>Навигация.</b>\nУзнайте про опасные районы, транспортные особенности (карта метро, система навигации), условия передвижения, приложения по геопозиции.\n\n👀<b>Общество.</b>\nНормы, этикет, социальные типы, рекомендации по общению с русскими, как правильно выйти из конфликта.\n\n🦻<b>Словарь.</b>\nЖаргонизмы, профессионализмы, традиционные выражения, шутки, особенности произношения.\n\n<b>⭐️Повседневная жизнь.</b>\nПопулярные сервисы и магазины.': 
			'<b>Great! Now there are several blocks available for you to explore.</b> (You can always return to this message using the /blocks command. To change the language, use /lang):\n\n\n🍾<b>Culture and trends.</b>\nFind out what is popular now: music, movies, art, entertainment and other activities: recommendations of places by category.\n\n👾<b>Navigation.</b>\nLearn about dangerous areas, transport features (metro map, navigation system), travel conditions, location applications.\n\n👀<b>Society.</b>\nNorms, etiquette, social types, recommendations for communicating with Russians, how to get out of the conflict correctly.\n\n🦻<b>Dictionary.</b>\nJargonisms, professionalism, traditional expressions, jokes, pronunciation features.\n\n<b>⭐️Everyday life.</b>\nPopular services and stores.',
	# инлайн кнопки блоков 
		'🍾Культура и тенденции': '🍾Culture and trends',
		'👾Навигация': '👾Navigation',
		'👀Общество': '👀Society',
		'🦻Словарь': '🦻Dictionary',
		'⭐️Повседневная жизнь': '⭐️Daily life',
		'ПОМЕНЯТЬ ЯЗЫК': 'CHANGE THE LANGUAGE',
	# перевод ссылок на картинки
		'https://i.postimg.cc/WzTrk6jK/blocksRU.png': 'https://i.postimg.cc/zv7hSbGf/blocksEN.png',
		'https://i.postimg.cc/WbDWbTWk/langRU.png': 'https://i.postimg.cc/pV5cPP1n/langEN.png',
	# перевод сообщений каждого блока 
		'Культура и тенденции: что популярно сейчас: музыка, кино, искусство, развлечения и другие активности: рекомендации мест по категориям.': 'Culture and trends: what is popular now: music, cinema, art, entertainment and other activities: recommendations of places by category.',
		'Навигация: опасные районы, транспортные особенности (карта метро, система навигации), условия передвижения, приложения по геопозиции.':'Navigation: dangerous areas, transport features (metro map, navigation system), travel conditions, geo-location applications.',
		'Словарь: жаргонизмы, профессионализмы, традиционные выражения, шутки, особенности произношения.':'Dictionary: jargonisms, professionalism, traditional expressions, jokes, pronunciation features.',
		'Общество: нормы, этикет, социальные типы, рекомендации по общению с русскими, как правильно выйти из конфликта.':'Society: norms, etiquette, social types, recommendations for communicating with Russians, how to get out of the conflict correctly.',
		'Повседневная жизнь: современные продуктовые тенденции, торговые центры/интернет-магазины, финансовая составляющая покупок.':'Daily life: modern food trends, shopping malls/online stores, financial component of purchases.',
		'<b>Как узнать расписания автобусов?</b>\nРасписание автобусов и прочего общественного транспорта можно узнать в приложениях "Яндекс Карта", "Google Карта" и подобные.\n\nОплата в общественном транспорте производится с помощью бакновских или льготных карт. Существует ряд льгот, позволяющие бесплатно пользоваться транспортом. Транспорт предусмотрен для людей с ограниченными возможностями.\n\n\n<b>Как пополнять проездные карты?</b>\nПополнить проездные карты можно либо в специальных приложениях, либо на местах, где стоят специальные автоматы для пополнения.':
			'<b>How do I find out the bus schedules?</b>\nThe schedule of buses and other public transport services can be found in the application "Yandex Map", "Google Map" and the like.\n\nPayment in public transport is made using bank or discount cards. There are a number of benefits that allow you to use transport for free. Transportation is provided for people with disabilities.\n\n\n<b>How do I top up my travel cards?</b>\nYou can replenish travel cards either in special applications or in places where there are special machines for replenishment.',
		'<b>Рекомендуется использовать следующие банки:</b>\n1. Сбербанк\n2. ВТБ\n3. Тинькофф\n4. Альфа-Банк\n5. Газпромбанк\n\n<b>Продуктовые магазины</b>\n1. Вкусвилл. Дорогая, но качественная, полезная еда. Товар сильно отличается от товаров в других магазинах.\n2. Пятёрочка. Самый популярный продуктовый магазин, где очень большой выбор продуктов по хорошей цене. \n3. Дикси. Низкие цены и редкие товары, но качество обслуживания может быть далеко не высоким.\n\n<b>Маркетплейсы</b>\n1. Avito. Платформа, где каждый может разместить объявление о продаже чего-либо, предоставлении различных услуг и свободных вакансиях на разные работы.\n2. Ozon/Wildberries. Онлайн магазины, где можно приобрести разные товары, начиная едой и заканчивая музыкальными инструментами. Доставка товаров производится в пункты выдачи, которые открыты почти в каждом районе.\n3. Aliexpress. Огромный выбор самых разных товаров, которых не найти больше нигде. Однако, существует проблема с долгими сроками доставки и ненадёжностью.':
			'<b>It is recommended to use the following jars:</b>\n1. Сбербанк\n2. ВТБ\n3. Тинькофф\n4. Альфа-Банк\n5. Газпромбанк\n\n<b>Grocery stores</b>\n1. Tasteville. Expensive, but high-quality, healthy food. The product is very different from the products in other stores.\n2. Pyaterochka. The most popular grocery store, where there is a very large selection of products at a good price. \n3. Dixie. Low prices and rare goods, but the quality of service may not be high.\n\n<b>Marketplaces</b>\n 1. Avito. A platform where everyone can place an ad for the sale of something, the provision of various services and vacancies for various jobs.\n2. Ozon/Wildberries. Online stores where you can buy various goods, starting with food and ending with musical instruments. Goods are delivered to pick-up points, which are open in almost every district.\n3. Aliexpress. A huge selection of various products that can not be found anywhere else. However, there is a problem with long delivery times and unreliability.',

	# прочие переводы
		'Блоки': 'Blocks',
		'Жаргонизмы':'Jargonisms',
		'Крылатые выражения':'Catch phrases',
		'Транспорт':'Transport',
		'Общественный транспорт':'Public transport',
	# Перевод картинок блоков
		'https://i.postimg.cc/HxC0J12W/1.jpg': 'https://i.postimg.cc/62rFpzPp/channel-dec-32.jpg',
		'https://i.postimg.cc/t7shbLQD/3.jpg': 'https://i.postimg.cc/YGsD9YCP/channel-dec-31-2.jpg',
		'https://i.postimg.cc/75TD9LmG/6.jpg': 'https://i.postimg.cc/5Y2BcDHz/channel-dec-34.jpg',
		'https://i.postimg.cc/18gxB9MT/5.jpg': 'https://i.postimg.cc/crLGK73d/channel-dec-33.jpg',

		'<b>Крылатые выражения</b>\n\n1. "Ни пуха, ни пера" - выражение, пожелание удачи.\n2. "Хоть кол на голове теши" - про очень упрямого человека.\n3. "Как с гуся вода" - о чем-то очень легком.\n4. "Умом Россию не понять" - о том, что Россия загадочная и сложная страна.\n5. "Пошел в ноль" - описывает событие, которое не оправдало ожиданий.\n6. "Не бояться волка, а бояться бабушку" - о неожиданном источнике проблем или опасности.\n7. "Бить баклуши" - означает надуться, делать вид, что чего-то не знаешь.\n8. "Дуракам закон не писан" - о том, что глупые люди могут делать что угодно.\n9. "Муха медовая" - о том, что что-то приятное и легкое.\n10. "Не пойми не примите" - выражение раздражения или удивления.\n11. "Ботинки на выброс" (значит, выгнать кого-то из партии или коллектива)\n12. "Стеклянные души" (люди, чувства которых очень хрупки)\n13. "Кустарник на печи" (непонятный, заумный разговор)\n14. "Рубаха на вырост" (как временное средство устранения недостатка)\n15. "Разбил животом" (проиграл, потерпел неудачу)\n16. "Дубиной мерить" (устрашать, давить силой)\n17. "Крокодил слёз не проливает" (о бесчувственности, равнодушии)\n18. "Солнце-сковорода" (очень жарко)\n19. "Маски шатки" (ложь, обман)\n20. "Поедет в коляске" (получит по заслугам)':
		 '<b>Catch phrases</b>\n\n1. "No fluff, no feather" - is an expression, a wish for good luck.\n2. "At least a stake on Tesh`s head" - is about a very stubborn person.\n3. "Like water off a goose" - is about something very light.\n4. "You can`t understand Russia with your mind" - that Russia is a mysterious and complex country.\n5. "Went to zero" - describes an event that did not meet expectations.\n6. "Not to be afraid of a wolf, but to be afraid of a grandmother" - about an unexpected source of problems or danger.\n7. "Beating the bucket" - means pouting, pretending that you don`t know something.\n8. "The law is not written for fools" - that stupid people can do anything.\n9. "Honey fly" - means that something is pleasant and easy.\n10. "Don`t understand, don`t accept" - is an expression of irritation or surprise.\n11. "Throw away shoes" - (means to kick someone out of the party or collective)\n12. "Glass souls" - (people whose feelings are very fragile)\n13. "Bush on the stove" - (incomprehensible, abstruse conversation)\n14. "Shirt for growth" - (as a temporary remedy)\n15. "Smashed with my stomach" - (lost, failed)\n16. "To measure with a club" - (to intimidate, to crush with force)\n17. "The crocodile does not shed tears" - (about insensitivity, indifference)\n18. "The sun is a frying pan" - (very hot)\n19. "Masks are shaky" (lies, deception)\n20. "He will go in a wheelchair" - (he will get what he deserves)',
		'<b>🚗Исходя из общего рейтинга исследования, тремя лучшими приложениями каршеринга признаны:</b>\n1. BelkaCar\n2. "Карусель"\n3. Anytime\n\n<b>🚕Для вызова такси отлично подходят:</b>\n1. ЯндексGo\n2. СитиМобил\n3. Uber':
			'<b>🚗Based on the overall rating of the study, the three best carsharing applications are recognized:</b>\n1. BelkaCar\n2. "Карусель"\n3. Anytime\n\n<b>🚕They are perfect for calling a taxi:</b>\n1. ЯндексGo\n2. СитиМобил\n3. Uber',
		'<b>Жаргонизмы</b>\n\n1. Мыло — электронная почта\nБаранка, бублик — руль\n2. Дирик — директор\n3. Фраер — напоказ модно одетый человек, наивный человек\n3. Кент — приятель, товарищ\n4. Мани, кеш, бабки — деньги\n5. Тачка — машина\n6. Пиар — способы продвижения и получения популярности в обществе\n7. Хайп — кратковременная популярность':'<b>Jargonisms</b>\n\n1. Soap — e-mail\n2. Steering wheel, bagel — steering wheel\n3. Diric — director\n4. Fraer — a fashionably dressed man, a naive man\n4. Kent — a friend\n5. Wheelbarrow — сar\n6. PR — ways to promote and gain popularity in society\n7. HYIP — short-term popularity'
	},


	'es': {
	# сообщение о блоках
		'<b>Отлично! Теперь вам доступно несколько блоков для изучения.</b> (Вы всегда сможете вернуться к этому сообщению, используя команду /blocks. Что бы поменять язык, используйте /lang):\n\n\n🍾<b>Культура и тенденции.</b>\nУзнайте, что популярно сейчас: музыка, кино, искусство, развлечения и другие активности: рекомендации мест по категориям.\n\n👾<b>Навигация.</b>\nУзнайте про опасные районы, транспортные особенности (карта метро, система навигации), условия передвижения, приложения по геопозиции.\n\n👀<b>Общество.</b>\nНормы, этикет, социальные типы, рекомендации по общению с русскими, как правильно выйти из конфликта.\n\n🦻<b>Словарь.</b>\nЖаргонизмы, профессионализмы, традиционные выражения, шутки, особенности произношения.\n\n<b>⭐️Повседневная жизнь.</b>\nПопулярные сервисы и магазины.': 
			'<b>¡Genial! Ahora hay varios bloques disponibles para explorar.</b> (Siempre podrá volver a esta publicación usando el comando /blocks. Para cambiar el idioma, use /lang):\n\n\n🍾<b>Cultura y tendencias.</b>\nDescubre lo que es popular ahora: música, cine, arte, entretenimiento y otras actividades: recomendaciones de lugares por categoría.\n\n👾<b>Navegación.</b>\nPuznayte sobre áreas peligrosas, características de transporte (mapa del metro, sistema de navegación), condiciones de movimiento, aplicaciones por ubicación geográfica.\n\n👀<b>Sociedad.</b>\nNormos, etiqueta, tipos sociales, recomendaciones para comunicarse con los rusos, cómo salir del conflicto.\n\n🦻<b>Diccionario.</b>\nArgonismos, profesionalismo, expresiones tradicionales, chistes, características de la pronunciación.\n\n<b>⭐️Vida Cotidiana.</b>\nServicios y tiendas populares.',
	# инлайн кнопки блоков 
		'🍾Культура и тенденции': '🍾Cultura y tendencias',
		'👾Навигация': '👾Navegación',
		'👀Общество': '👀Sociedad',
		'🦻Словарь': '🦻Diccionario',
		'⭐️Повседневная жизнь': '⭐️Vida cotidiana',
		'ПОМЕНЯТЬ ЯЗЫК': 'CAMBIAR IDIOMA',
	# перевод ссылок на картинки 
		'https://i.postimg.cc/WzTrk6jK/blocksRU.png': 'https://i.postimg.cc/tThWJm0W/blocksES.png',
		'https://i.postimg.cc/WbDWbTWk/langRU.png': 'https://i.postimg.cc/CK6JV2GN/langES.png',
	# перевод сообщений каждого блока
		'Культура и тенденции: что популярно сейчас: музыка, кино, искусство, развлечения и другие активности: рекомендации мест по категориям.': 'Cultura y tendencias: lo que es popular ahora: música, cine, arte, entretenimiento y otras actividades: recomendaciones de lugares por categoría.',
		'Навигация: опасные районы, транспортные особенности (карта метро, система навигации), условия передвижения, приложения по геопозиции.':'Navegación: áreas peligrosas, características de transporte (mapa del metro, sistema de navegación), condiciones de movimiento, aplicaciones por ubicación.',
		'Словарь: жаргонизмы, профессионализмы, традиционные выражения, шутки, особенности произношения.':'Vocabulario: jerga, profesionalismo, expresiones tradicionales, chistes, características de pronunciación.',
		'Общество: нормы, этикет, социальные типы, рекомендации по общению с русскими, как правильно выйти из конфликта.':'Sociedad: normas, etiqueta, tipos sociales, recomendaciones para comunicarse con los rusos, cómo salir del conflicto.',
		'Повседневная жизнь: современные продуктовые тенденции, торговые центры/интернет-магазины, финансовая составляющая покупок.':'Vida cotidiana: tendencias modernas de comestibles, centros comerciales/tiendas en línea, el componente financiero de las compras.',
		'<b>Как узнать расписания автобусов?</b>\nРасписание автобусов и прочего общественного транспорта можно узнать в приложениях "Яндекс Карта", "Google Карта" и подобные.\n\nОплата в общественном транспорте производится с помощью бакновских или льготных карт. Существует ряд льгот, позволяющие бесплатно пользоваться транспортом. Транспорт предусмотрен для людей с ограниченными возможностями.\n\n\n<b>Как пополнять проездные карты?</b>\nПополнить проездные карты можно либо в специальных приложениях, либо на местах, где стоят специальные автоматы для пополнения.':
			'<b>¿Cómo saber los horarios de los autobuses?</b>\nLos horarios de los autobuses y otros transportes públicos se pueden encontrar en las aplicaciones "Yandex Map", "Google Map" y similares.\n\nEl pago en transporte público se realiza a través de tarjetas bancarias o preferenciales. Hay una serie de ventajas que permiten el uso gratuito del transporte. El transporte está reservado para personas con discapacidad.\n\n\n<b>¿Cómo reponer tarjetas de viaje?</b>\nPuede recargar las tarjetas de viaje en aplicaciones especiales o en lugares donde hay máquinas especiales para recargar.',
		'<b>Рекомендуется использовать следующие банки:</b>\n1. Сбербанк\n2. ВТБ\n3. Тинькофф\n4. Альфа-Банк\n5. Газпромбанк\n\n<b>Продуктовые магазины</b>\n1. Вкусвилл. Дорогая, но качественная, полезная еда. Товар сильно отличается от товаров в других магазинах.\n2. Пятёрочка. Самый популярный продуктовый магазин, где очень большой выбор продуктов по хорошей цене. \n3. Дикси. Низкие цены и редкие товары, но качество обслуживания может быть далеко не высоким.\n\n<b>Маркетплейсы</b>\n1. Avito. Платформа, где каждый может разместить объявление о продаже чего-либо, предоставлении различных услуг и свободных вакансиях на разные работы.\n2. Ozon/Wildberries. Онлайн магазины, где можно приобрести разные товары, начиная едой и заканчивая музыкальными инструментами. Доставка товаров производится в пункты выдачи, которые открыты почти в каждом районе.\n3. Aliexpress. Огромный выбор самых разных товаров, которых не найти больше нигде. Однако, существует проблема с долгими сроками доставки и ненадёжностью.':
			'<b>Se recomienda utilizar los siguientes frascos:</b>\n1. Сбербанк\n2. ВТБ\n3. Тинькофф\n4. Альфа-Банк\n5. Газпромбанк\n\n<b>Tiendas de comestibles</b>\n1. Sabor. Comida cara, pero de calidad, saludable. El producto es muy diferente de los productos en otras tiendas.\n2. Cinco. La tienda de comestibles más popular donde hay una gran selección de productos a buen precio.\n3. Dixie. Precios bajos y productos raros, pero la calidad del Servicio puede estar lejos de ser alta.\n\n<b>Marketplays</b>\n1. Avito. Una plataforma donde todos pueden colocar un anuncio para vender algo, proporcionar diferentes servicios y vacantes para diferentes trabajos.\n2. Ozon/Wildberries. Tiendas en línea donde se pueden comprar diferentes productos, desde comida hasta instrumentos musicales. La entrega de los productos se realiza en los puntos de recogida, que están abiertos en casi todos los distritos.\n3. Aliexpress. Una gran variedad de productos que no se encuentran en ningún otro lugar. Sin embargo, hay un problema con los largos plazos de entrega y la falta de fiabilidad.',
	# прочие переводы
		'Блоки': 'Bloques',
		'Жаргонизмы':'Jergas',
		'Крылатые выражения':'Expresiones aladas',
		'Транспорт':'Transporte',
		'Общественный транспорт':'Transporte público',
	# Перевод картинок блоков 
		'https://i.postimg.cc/HxC0J12W/1.jpg': 'https://i.postimg.cc/NLygQwsN/channel-dec-32-2.jpg',
		'https://i.postimg.cc/t7shbLQD/3.jpg': 'https://i.postimg.cc/VJ0fLWsx/channel-dec-31.jpg',
		'https://i.postimg.cc/75TD9LmG/6.jpg': 'https://i.postimg.cc/7C34vWvq/channel-dec-34-2.jpg',
		'https://i.postimg.cc/18gxB9MT/5.jpg': 'https://i.postimg.cc/K3ZSDBsr/channel-dec-33-2.jpg',

		'<b>🚗Исходя из общего рейтинга исследования, тремя лучшими приложениями каршеринга признаны:</b>\n1. BelkaCar\n2. "Карусель"\n3. Anytime\n\n<b>🚕Для вызова такси отлично подходят:</b>\n1. ЯндексGo\n2. СитиМобил\n3. Uber':
			'<b>🚗Según la clasificación general del estudio, se reconocen las tres mejores aplicaciones de CarShare:</b>\n1. BelkaCar\n2. "Карусель"\n3. Anytime\n\n<b>🚕Para llamar a un taxi son excelentes:</b>\n1. ЯндексGo\n2. СитиМобил\n3. Uber',
		'<b>Крылатые выражения</b>\n\n1. "Ни пуха, ни пера" - выражение, пожелание удачи.\n2. "Хоть кол на голове теши" - про очень упрямого человека.\n3. "Как с гуся вода" - о чем-то очень легком.\n4. "Умом Россию не понять" - о том, что Россия загадочная и сложная страна.\n5. "Пошел в ноль" - описывает событие, которое не оправдало ожиданий.\n6. "Не бояться волка, а бояться бабушку" - о неожиданном источнике проблем или опасности.\n7. "Бить баклуши" - означает надуться, делать вид, что чего-то не знаешь.\n8. "Дуракам закон не писан" - о том, что глупые люди могут делать что угодно.\n9. "Муха медовая" - о том, что что-то приятное и легкое.\n10. "Не пойми не примите" - выражение раздражения или удивления.\n11. "Ботинки на выброс" (значит, выгнать кого-то из партии или коллектива)\n12. "Стеклянные души" (люди, чувства которых очень хрупки)\n13. "Кустарник на печи" (непонятный, заумный разговор)\n14. "Рубаха на вырост" (как временное средство устранения недостатка)\n15. "Разбил животом" (проиграл, потерпел неудачу)\n16. "Дубиной мерить" (устрашать, давить силой)\n17. "Крокодил слёз не проливает" (о бесчувственности, равнодушии)\n18. "Солнце-сковорода" (очень жарко)\n19. "Маски шатки" (ложь, обман)\n20. "Поедет в коляске" (получит по заслугам)':
		 '<b>Expresiones aladas</b>\n\n1. "Ni pelusa, ni pluma" - es una expresión, un deseo de buena suerte.\n2. "Al menos una estaca en la cabeza de tesha" - es sobre una persona muy obstinada.\n3. "Como el agua de un ganso" - sobre algo muy fácil.\n4. "La mente no entiende a Rusia" - que Rusia es un país misterioso y complejo.\n5. "Se fue a cero" - describe un evento que no cumplió con las expectativas.\n6. "No temer al lobo, sino temer a la abuela" - sobre una fuente inesperada de problemas o peligro.\n7. "Patear los Pulgares" - significa exagerar, fingir que no sabes algo.\n8. "La ley no está escrita para los tontos" - que las personas estúpidas pueden hacer cualquier cosa.\n9. "La mosca de la miel" - sobre el hecho de que algo agradable y fácil.\n10. "No comprendas no aceptes" - es una expresión de irritación o sorpresa.\n11. "Botas de expulsión" - (significa expulsar a alguien de un partido o equipo)\n12. "Almas de cristal" - (personas cuyos sentimientos son muy frágiles)\n13. "Arbusto en el horno " - (conversación incomprensible y aberrante)\n14. "Camisa para el crecimiento" - (como un remedio temporal para la deficiencia)\n15. "Aplastado por el estómago" - (perdido, fallado)\n16. "Medir porras" - (asustar, presionar por la fuerza)\n17. "El cocodrilo no derrama lágrimas" - (sobre la insensibilidad, la indiferencia)\n18. "Sol-sartén" - (muy caliente)\n19. "Máscaras shatka" - (mentira, engaño)\n20. "Va en silla de ruedas" - (recibirá lo que merece)',
		'<b>Жаргонизмы</b>\n\n1. Мыло — электронная почта\nБаранка, бублик — руль\n2. Дирик — директор\n3. Фраер — напоказ модно одетый человек, наивный человек\n3. Кент — приятель, товарищ\n4. Мани, кеш, бабки — деньги\n5. Тачка — машина\n6. Пиар — способы продвижения и получения популярности в обществе\n7. Хайп — кратковременная популярность':'<b>Jergas</b>\n\n1. Jabón — correo electrónico\n2. Carnero, Bagel — volante\n3. Dirik — director\n4. Fryer — hombre vestido de moda, hombre ingenuo\n5. Kent — amigo, compañero\n6. Mani, caché, abuela-dinero\n7. Carretilla — máquina de relaciones\n8. HYIP — popularidad a corto plazo'
	}	
}
	



# -------------------------------------------------------------------------------
# ПЕРЕВОД ТЕКСТА
# -------------------------------------------------------------------------------
def ll(text,lang='ru'):
	if lang == 'ru':
		return text
	else:
		global trans
		try:
			return trans[lang][text]
		except:
			return text