trans = {
	'en': {
	# сообщение о блоках
		'<b>Отлично! Теперь вам доступно несколько блоков для изучения.</b> (Вы всегда сможете вернуться к этому сообщению, используя команду /blocks. Что бы поменять язык, используйте /lang):\n\n\n🍾<b>Культура и тенденции.</b>\nУзнайте, что популярно сейчас: музыка, кино, искусство, развлечения и другие активности: рекомендации мест по категориям.\n\n👾<b>Навигация.</b>\nУзнайте про опасные районы, транспортные особенности (карта метро, система навигации), условия передвижения, приложения по геопозиции.\n\n👀<b>Общество.</b>\nНормы, этикет, социальные типы, рекомендации по общению с русскими, как правильно выйти из конфликта.\n\n🦻<b>Словарь.</b>\nЖаргонизмы, профессионализмы, традиционные выражения, шутки, особенности произношения.\n\n<b>⭐️Повседневная жизнь.</b>\nПопулярные сервисы и магазины.': 
			'<b>Great! Now there are several blocks available for you to explore.</b> (You can always return to this message using the /blocks command. To change the language, use /lang):\n\n\n🍾<b>Culture and trends.</b>\nFind out what is popular now: music, movies, art, entertainment and other activities: recommendations of places by category.\n\n👾<b>Navigation.</b>\nLearn about dangerous areas, transport features (metro map, navigation system), travel conditions, location applications.\n\n👀<b>Society.</b>\nNorms, etiquette, social types, recommendations for communicating with Russians, how to get out of the conflict correctly.\n\n🦻<b>Dictionary.</b>\nJargonisms, professionalism, traditional expressions, jokes, pronunciation features.\n\n<b>⭐️Everyday life.</b>\nPopular services and stores.',
	# инлайн кнопки блоков 
		'🍾Культура и тенденции': '🍾Culture and trends',
		'👾Навигация': '👾Navigation',
		'👀Общество': '👀Society',
		'🦻Словарь': '🦻Dictionary',
		'⭐️Повседневная жизнь': '⭐️Daily life',
		'ПОМЕНЯТЬ ЯЗЫК': 'CHANGE THE LANGUAGE',
	# перевод ссылок на картинки
		'https://i.postimg.cc/zLfG3J86/bl.jpg': 'https://i.postimg.cc/fV8MG6mK/bl1.jpg',
		'https://i.postimg.cc/6yN6nVBd/channel-dec-30-3.jpg': 'https://i.postimg.cc/D8dvgWzR/channel-dec-31-3.jpg',
	# перевод сообщений каждого блока 
		'Культура и тенденции: что популярно сейчас: музыка, кино, искусство, развлечения и другие активности: рекомендации мест по категориям.': 'Culture and trends: what is popular now: music, cinema, art, entertainment and other activities: recommendations of places by category.',
		'Навигация: опасные районы, транспортные особенности (карта метро, система навигации), условия передвижения, приложения по геопозиции.':'Navigation: dangerous areas, transport features (metro map, navigation system), travel conditions, geo-location applications.',
		'Словарь: жаргонизмы, профессионализмы, традиционные выражения, шутки, особенности произношения.':'Dictionary: jargonisms, professionalism, traditional expressions, jokes, pronunciation features.',
		'Общество: нормы, этикет, социальные типы, рекомендации по общению с русскими, как правильно выйти из конфликта.':'Society: norms, etiquette, social types, recommendations for communicating with Russians, how to get out of the conflict correctly.',
		'Повседневная жизнь: современные продуктовые тенденции, торговые центры/интернет-магазины, финансовая составляющая покупок.':'Daily life: modern food trends, shopping malls/online stores, financial component of purchases.',
		'<b>Как узнать расписания автобусов?</b>\nРасписание автобусов и прочего общественного транспорта можно узнать в приложениях "Яндекс Карта", "Google Карта" и подобные.\n\nОплата в общественном транспорте производится с помощью бакновских или льготных карт. Существует ряд льгот, позволяющие бесплатно пользоваться транспортом. Транспорт предусмотрен для людей с ограниченными возможностями.\n\n\n<b>Как пополнять проездные карты?</b>\nПополнить проездные карты можно либо в специальных приложениях, либо на местах, где стоят специальные автоматы для пополнения.':
			'<b>How do I find out the bus schedules?</b>\nThe schedule of buses and other public transport services can be found in the application "Yandex Map", "Google Map" and the like.\n\nPayment in public transport is made using bank or discount cards. There are a number of benefits that allow you to use transport for free. Transportation is provided for people with disabilities.\n\n\n<b>How do I top up my travel cards?</b>\nYou can replenish travel cards either in special applications or in places where there are special machines for replenishment.',
		'<b>Рекомендуется использовать следующие банки:</b>\n1. Сбербанк\n2. ВТБ\n3. Тинькофф\n4. Альфа-Банк\n5. Газпромбанк\n\n<b>Продуктовые магазины</b>\n1. Вкусвилл. Дорогая, но качественная, полезная еда. Товар сильно отличается от товаров в других магазинах.\n2. Пятёрочка. Самый популярный продуктовый магазин, где очень большой выбор продуктов по хорошей цене. \n3. Дикси. Низкие цены и редкие товары, но качество обслуживания может быть далеко не высоким.\n\n<b>Маркетплейсы</b>\n1. Avito. Платформа, где каждый может разместить объявление о продаже чего-либо, предоставлении различных услуг и свободных вакансиях на разные работы.\n2. Ozon/Wildberries. Онлайн магазины, где можно приобрести разные товары, начиная едой и заканчивая музыкальными инструментами. Доставка товаров производится в пункты выдачи, которые открыты почти в каждом районе.\n3. Aliexpress. Огромный выбор самых разных товаров, которых не найти больше нигде. Однако, существует проблема с долгими сроками доставки и ненадёжностью.':
			'<b>It is recommended to use the following jars:</b>\n1. Сбербанк\n2. ВТБ\n3. Тинькофф\n4. Альфа-Банк\n5. Газпромбанк\n\n<b>Grocery stores</b>\n1. Tasteville. Expensive, but high-quality, healthy food. The product is very different from the products in other stores.\n2. Pyaterochka. The most popular grocery store, where there is a very large selection of products at a good price. \n3. Dixie. Low prices and rare goods, but the quality of service may not be high.\n\n<b>Marketplaces</b>\n 1. Avito. A platform where everyone can place an ad for the sale of something, the provision of various services and vacancies for various jobs.\n2. Ozon/Wildberries. Online stores where you can buy various goods, starting with food and ending with musical instruments. Goods are delivered to pick-up points, which are open in almost every district.\n3. Aliexpress. A huge selection of various products that can not be found anywhere else. However, there is a problem with long delivery times and unreliability.',

	# прочие переводы
		'Блоки': 'Blocks',
		'Жаргонизмы':'Jargonisms',
		'Крылатые выражения':'Catch phrases',
		'Транспорт':'Transport',
		'Общественный транспорт':'Public transport',
	# Перевод картинок блоков
		'https://i.postimg.cc/HxC0J12W/1.jpg': 'https://i.postimg.cc/62rFpzPp/channel-dec-32.jpg',
		'https://i.postimg.cc/t7shbLQD/3.jpg': 'https://i.postimg.cc/YGsD9YCP/channel-dec-31-2.jpg',
		'https://i.postimg.cc/75TD9LmG/6.jpg': 'https://i.postimg.cc/5Y2BcDHz/channel-dec-34.jpg',
		'https://i.postimg.cc/18gxB9MT/5.jpg': 'https://i.postimg.cc/crLGK73d/channel-dec-33.jpg',
		'https://i.postimg.cc/bssMYrG4/4.jpg': 'https://i.postimg.cc/XpmPrWdq/channel-dec-35.jpg',


		# общество 
		'Почему посторонний может спросить сигарету или зажигалку?':'Why would an outsider ask for a cigarette or a lighter?',																											
		'Почему русские угрюмые?':'Why are Russians sullen?',
		'Кто такой гопник?':'Who is a gopnik?',
		'Кто такие маргиналы и где их можно встретить?':'Who are the marginals and where can they be found?',
		'Почему люди собираются у подъезда?':'Why are people gathering at the entrance?',
		'Кто такие алкаши, пьянь?':'Who are drunks, drunks?',
		'На какие части делится Москва?':'What parts is Moscow divided into?',
		'Как принято говорить между собой у русских, присутствует ли у них жестикуляция, как они обращаются друг к другу?':'How do Russians talk to each other, do they have gestures, how do they address each other?',
		'Как здороваются русские?':'How do Russians greet each other?',
		'Как в России относятся к женщинам?':'How are women treated in Russia?',
		'Как в России относятся к мужчинам?':'How are men treated in Russia?',
		'Как прощаются русские?':'How do Russians say goodbye?',
		'Как в России относятся к ЛГБТ?':'How do they treat LGBT people in Russia?',

		#общество ответы
		'Лучше выполнить его просьбу, если у вас действительно есть сигарета или зажигалка или все вместе. Это обычная просьба и в ней нет скрытого смысла. Человек обязательно поблагодарит вас за то что вы с ним и оставит вас в покое. Однако следует обращать внимание на внешний вид оппонента: если он опрятный и трезвый не бойтесь поделиться. Но начинать с этого момента диалог не принято. Если перед вами пьяный неопрятный человек, лучше сказать, что у вас нет ни сигареты ни зажигалки, и извиниться. Тогда человек отстанет от вас.':'It is better to fulfill his request if you really have a cigarette or a lighter or both. This is an ordinary request and there is no hidden meaning in it. The person will definitely thank you for being with him and leave you alone. However, you should pay attention to the appearance of your opponent: if he is neat and sober, do not be afraid to share. But it is not accepted to start a dialogue from this moment. If you have a drunken, untidy person in front of you, it`s better to say that you don`t have a cigarette or a lighter, and apologize. Then the person will leave you alone.',
		'Русские не любят улыбаться без уважительной причины. Более того, в России любого, кто постоянно вежливо улыбается, считают неискренним, скрытным человеком, который отказывается показывать свои истинные чувства.':'Russians don`t like to smile without a good reason. Moreover, in Russia, anyone who constantly politely smiles is considered an insincere, secretive person who refuses to show his true feelings.',
		'Люди, ведущие разгульный образ жизни. Их можно определить по характерному внешнему виду: это спортивный костюм (Adidas, Puma, Nike), кепка на голове и немного неадекватнык вид. От них лучше держаться подальше, так как они могут быть вспыльчивы и наглы.':'People who lead a debauched lifestyle. They can be identified by their characteristic appearance: this is a tracksuit (Adidas, Puma, Nike), a cap on his head and a slightly inadequate look. It is better to stay away from them, as they can be short-tempered and arrogant.',
		'У подъезда или в подъезде чаще всего, в метро, в темное время суток.':'At the entrance or in the entrance, most often, in the subway, at night',
		'В спальных районах Москвы принято собираться у подъезда человека, который организовал встречу. Таким образом, если нет определенной цели куда направиться и чем заняться, люди выясняют это на месте. У подъезда встречаются, потому что чаще всего, если люди живут рядом, то таким образом удобнее и понятнее удается пересечься.':'In residential areas of Moscow, it is customary to gather at the entrance of the person who organized the meeting. Thus, if there is no specific goal where to go and what to do, people figure it out on the spot. They meet at the entrance, because most often, if people live nearby, then it is more convenient and understandable to cross paths.',
		'Местная маргиналия. Тот самый стереотип за рубежом, расценивающий менталитет русских. Алкоголики, которые из самого дешёвого алкоголя выбирают водку или пиво.':'Local marginalia. That is the stereotype abroad, regarding the mentality of Russians. Alcoholics who choose vodka or beer from the cheapest alcohol.',
		'Россия — страна с федеральной форомой административного деления. Москва — город федерального значения, который так же делится на субъекты, которые могут влиять на решения московской думы. Районы Москвы отличаются ценообразованием, архитектурой и даже культурой.':'Russia is a country with a federal form of administrative division. Moscow is a city of federal significance, which is also divided into subjects that can influence the decisions of the Moscow Duma. Moscow`s districts differ in pricing, architecture, and even culture.',
		'Изначально к незнакомому человеку принято обращаться на вы, далее, спустя продолжительность общения люди договариваются как им комфортнее, чтобы к ним обращались. Почти всегда далее люди переходят к обращению на ты. Русские: открытые люди, просто им требуется чуть больше одной встречи, чтобы раскрыться. Однако они готовы помочь любому нуждающемуся в помощи, если он об этом попросит.':'Initially, it is customary to address a stranger to you, then, after a period of communication, people agree on how comfortable they are to be addressed. Almost always, people go on to address you. Russians: open people, it just takes them a little more than one meeting to open up. However, they are ready to help anyone in need of help if they ask for it.',
		'Встретившись с приятелем в неформальной обстановке обмениваются улыбкой, здороваются в принятой манере(обычно это: Привет! Здорово!)пожимают руку, обнимаются.\nВ формальной обстановке русские одаривают сдержанной улыбкой в знак вежливости(но также зависит от их персонального настроения) и пожимают руку, предоставившись.':'After meeting with a friend in an informal setting, they exchange a smile, greet in an accepted manner (usually this is: Hello! Great!)They shake hands and hug.\nIn a formal setting, Russians give a restrained smile as a sign of politeness (but also depends on their personal mood) and shake hands, having been provided.',
		'На равных, как и к мужчинам. В обществе с женщинами обращаются вежливо и уважительно: придерживают двери, уступают место.':'On equal terms, as well as to men. In society, women are treated politely and respectfully: they hold the doors, give way',
		'Уважительно и на равных, главное, соблюдать принятый образ поведения: строгий и сдержанный, но при этом брутальный, чтобы не возникало лишних вопросов.':'Respectfully and on equal terms, the main thing is to observe the accepted way of behavior: strict and restrained, but at the same time brutal, so that no unnecessary questions arise.',
		'На прощание русские говорят "До свидания!". Смысл слова заключается в том, что прощающиеся надеятся на встречи в дальнейшем. Они желают удачи и искренне желают встретиться еще.':'At parting, Russians say "Goodbye!". The meaning of the word is that those saying goodbye hope to meet in the future. They wish you good luck and sincerely wish to meet again.',
		'В обществе отношение довольно нейтрально. Официально:\n30 ноября 2023 года судья Верховного суда РФ Олег Нефёдов объявил «экстремистской организацией» и запретил «международное общественное движение ЛГБТ».':'The attitude in society is quite neutral. Officially:\nOn November 30, 2023, Oleg Nefedov, a judge of the Supreme Court of the Russian Federation, declared an "extremist organization" and banned the "international LGBT social movement".',






		'<b>Крылатые выражения</b>\n\n1. "Ни пуха, ни пера" - выражение, пожелание удачи.\n2. "Хоть кол на голове теши" - про очень упрямого человека.\n3. "Как с гуся вода" - о чем-то очень легком.\n4. "Умом Россию не понять" - о том, что Россия загадочная и сложная страна.\n5. "Пошел в ноль" - описывает событие, которое не оправдало ожиданий.\n6. "Не бояться волка, а бояться бабушку" - о неожиданном источнике проблем или опасности.\n7. "Бить баклуши" - означает надуться, делать вид, что чего-то не знаешь.\n8. "Дуракам закон не писан" - о том, что глупые люди могут делать что угодно.\n9. "Муха медовая" - о том, что что-то приятное и легкое.\n10. "Не пойми не примите" - выражение раздражения или удивления.\n11. "Ботинки на выброс" (значит, выгнать кого-то из партии или коллектива)\n12. "Стеклянные души" (люди, чувства которых очень хрупки)\n13. "Кустарник на печи" (непонятный, заумный разговор)\n14. "Рубаха на вырост" (как временное средство устранения недостатка)\n15. "Разбил животом" (проиграл, потерпел неудачу)\n16. "Дубиной мерить" (устрашать, давить силой)\n17. "Крокодил слёз не проливает" (о бесчувственности, равнодушии)\n18. "Солнце-сковорода" (очень жарко)\n19. "Маски шатки" (ложь, обман)\n20. "Поедет в коляске" (получит по заслугам)':
		 '<b>Catch phrases</b>\n\n1. "No fluff, no feather" - is an expression, a wish for good luck.\n2. "At least a stake on Tesh`s head" - is about a very stubborn person.\n3. "Like water off a goose" - is about something very light.\n4. "You can`t understand Russia with your mind" - that Russia is a mysterious and complex country.\n5. "Went to zero" - describes an event that did not meet expectations.\n6. "Not to be afraid of a wolf, but to be afraid of a grandmother" - about an unexpected source of problems or danger.\n7. "Beating the bucket" - means pouting, pretending that you don`t know something.\n8. "The law is not written for fools" - that stupid people can do anything.\n9. "Honey fly" - means that something is pleasant and easy.\n10. "Don`t understand, don`t accept" - is an expression of irritation or surprise.\n11. "Throw away shoes" - (means to kick someone out of the party or collective)\n12. "Glass souls" - (people whose feelings are very fragile)\n13. "Bush on the stove" - (incomprehensible, abstruse conversation)\n14. "Shirt for growth" - (as a temporary remedy)\n15. "Smashed with my stomach" - (lost, failed)\n16. "To measure with a club" - (to intimidate, to crush with force)\n17. "The crocodile does not shed tears" - (about insensitivity, indifference)\n18. "The sun is a frying pan" - (very hot)\n19. "Masks are shaky" (lies, deception)\n20. "He will go in a wheelchair" - (he will get what he deserves)',
		'<b>🚗Исходя из общего рейтинга исследования, тремя лучшими приложениями каршеринга признаны:</b>\n1. BelkaCar\n2. "Карусель"\n3. Anytime\n\n<b>🚕Для вызова такси отлично подходят:</b>\n1. ЯндексGo\n2. СитиМобил\n3. Uber':
			'<b>🚗Based on the overall rating of the study, the three best carsharing applications are recognized:</b>\n1. BelkaCar\n2. "Карусель"\n3. Anytime\n\n<b>🚕They are perfect for calling a taxi:</b>\n1. ЯндексGo\n2. СитиМобил\n3. Uber',
		'<b>Жаргонизмы</b>\n\n1. Мыло — электронная почта\nБаранка, бублик — руль\n2. Дирик — директор\n3. Фраер — напоказ модно одетый человек, наивный человек\n3. Кент — приятель, товарищ\n4. Мани, кеш, бабки — деньги\n5. Тачка — машина\n6. Пиар — способы продвижения и получения популярности в обществе\n7. Хайп — кратковременная популярность':'<b>Jargonisms</b>\n\n1. Soap — e-mail\n2. Steering wheel, bagel — steering wheel\n3. Diric — director\n4. Fraer — a fashionably dressed man, a naive man\n4. Kent — a friend\n5. Wheelbarrow — сar\n6. PR — ways to promote and gain popularity in society\n7. HYIP — short-term popularity'
	},


	'es': {
	# сообщение о блоках
		'<b>Отлично! Теперь вам доступно несколько блоков для изучения.</b> (Вы всегда сможете вернуться к этому сообщению, используя команду /blocks. Что бы поменять язык, используйте /lang):\n\n\n🍾<b>Культура и тенденции.</b>\nУзнайте, что популярно сейчас: музыка, кино, искусство, развлечения и другие активности: рекомендации мест по категориям.\n\n👾<b>Навигация.</b>\nУзнайте про опасные районы, транспортные особенности (карта метро, система навигации), условия передвижения, приложения по геопозиции.\n\n👀<b>Общество.</b>\nНормы, этикет, социальные типы, рекомендации по общению с русскими, как правильно выйти из конфликта.\n\n🦻<b>Словарь.</b>\nЖаргонизмы, профессионализмы, традиционные выражения, шутки, особенности произношения.\n\n<b>⭐️Повседневная жизнь.</b>\nПопулярные сервисы и магазины.': 
			'<b>¡Genial! Ahora hay varios bloques disponibles para explorar.</b> (Siempre podrá volver a esta publicación usando el comando /blocks. Para cambiar el idioma, use /lang):\n\n\n🍾<b>Cultura y tendencias.</b>\nDescubre lo que es popular ahora: música, cine, arte, entretenimiento y otras actividades: recomendaciones de lugares por categoría.\n\n👾<b>Navegación.</b>\nPuznayte sobre áreas peligrosas, características de transporte (mapa del metro, sistema de navegación), condiciones de movimiento, aplicaciones por ubicación geográfica.\n\n👀<b>Sociedad.</b>\nNormos, etiqueta, tipos sociales, recomendaciones para comunicarse con los rusos, cómo salir del conflicto.\n\n🦻<b>Diccionario.</b>\nArgonismos, profesionalismo, expresiones tradicionales, chistes, características de la pronunciación.\n\n<b>⭐️Vida Cotidiana.</b>\nServicios y tiendas populares.',
	# инлайн кнопки блоков 
		'🍾Культура и тенденции': '🍾Cultura y tendencias',
		'👾Навигация': '👾Navegación',
		'👀Общество': '👀Sociedad',
		'🦻Словарь': '🦻Diccionario',
		'⭐️Повседневная жизнь': '⭐️Vida cotidiana',
		'ПОМЕНЯТЬ ЯЗЫК': 'CAMBIAR IDIOMA',
	# перевод ссылок на картинки 
		'https://i.postimg.cc/zLfG3J86/bl.jpg': 'https://i.postimg.cc/0zk8H8Mj/bl-2.jpg',
		'https://i.postimg.cc/6yN6nVBd/channel-dec-30-3.jpg': 'https://i.postimg.cc/kRWnLGv6/channel-dec-32-3.jpg',
	# перевод сообщений каждого блока
		'Культура и тенденции: что популярно сейчас: музыка, кино, искусство, развлечения и другие активности: рекомендации мест по категориям.': 'Cultura y tendencias: lo que es popular ahora: música, cine, arte, entretenimiento y otras actividades: recomendaciones de lugares por categoría.',
		'Навигация: опасные районы, транспортные особенности (карта метро, система навигации), условия передвижения, приложения по геопозиции.':'Navegación: áreas peligrosas, características de transporte (mapa del metro, sistema de navegación), condiciones de movimiento, aplicaciones por ubicación.',
		'Словарь: жаргонизмы, профессионализмы, традиционные выражения, шутки, особенности произношения.':'Vocabulario: jerga, profesionalismo, expresiones tradicionales, chistes, características de pronunciación.',
		'Общество: нормы, этикет, социальные типы, рекомендации по общению с русскими, как правильно выйти из конфликта.':'Sociedad: normas, etiqueta, tipos sociales, recomendaciones para comunicarse con los rusos, cómo salir del conflicto.',
		'Повседневная жизнь: современные продуктовые тенденции, торговые центры/интернет-магазины, финансовая составляющая покупок.':'Vida cotidiana: tendencias modernas de comestibles, centros comerciales/tiendas en línea, el componente financiero de las compras.',
		'<b>Как узнать расписания автобусов?</b>\nРасписание автобусов и прочего общественного транспорта можно узнать в приложениях "Яндекс Карта", "Google Карта" и подобные.\n\nОплата в общественном транспорте производится с помощью бакновских или льготных карт. Существует ряд льгот, позволяющие бесплатно пользоваться транспортом. Транспорт предусмотрен для людей с ограниченными возможностями.\n\n\n<b>Как пополнять проездные карты?</b>\nПополнить проездные карты можно либо в специальных приложениях, либо на местах, где стоят специальные автоматы для пополнения.':
			'<b>¿Cómo saber los horarios de los autobuses?</b>\nLos horarios de los autobuses y otros transportes públicos se pueden encontrar en las aplicaciones "Yandex Map", "Google Map" y similares.\n\nEl pago en transporte público se realiza a través de tarjetas bancarias o preferenciales. Hay una serie de ventajas que permiten el uso gratuito del transporte. El transporte está reservado para personas con discapacidad.\n\n\n<b>¿Cómo reponer tarjetas de viaje?</b>\nPuede recargar las tarjetas de viaje en aplicaciones especiales o en lugares donde hay máquinas especiales para recargar.',
		'<b>Рекомендуется использовать следующие банки:</b>\n1. Сбербанк\n2. ВТБ\n3. Тинькофф\n4. Альфа-Банк\n5. Газпромбанк\n\n<b>Продуктовые магазины</b>\n1. Вкусвилл. Дорогая, но качественная, полезная еда. Товар сильно отличается от товаров в других магазинах.\n2. Пятёрочка. Самый популярный продуктовый магазин, где очень большой выбор продуктов по хорошей цене. \n3. Дикси. Низкие цены и редкие товары, но качество обслуживания может быть далеко не высоким.\n\n<b>Маркетплейсы</b>\n1. Avito. Платформа, где каждый может разместить объявление о продаже чего-либо, предоставлении различных услуг и свободных вакансиях на разные работы.\n2. Ozon/Wildberries. Онлайн магазины, где можно приобрести разные товары, начиная едой и заканчивая музыкальными инструментами. Доставка товаров производится в пункты выдачи, которые открыты почти в каждом районе.\n3. Aliexpress. Огромный выбор самых разных товаров, которых не найти больше нигде. Однако, существует проблема с долгими сроками доставки и ненадёжностью.':
			'<b>Se recomienda utilizar los siguientes frascos:</b>\n1. Сбербанк\n2. ВТБ\n3. Тинькофф\n4. Альфа-Банк\n5. Газпромбанк\n\n<b>Tiendas de comestibles</b>\n1. Sabor. Comida cara, pero de calidad, saludable. El producto es muy diferente de los productos en otras tiendas.\n2. Cinco. La tienda de comestibles más popular donde hay una gran selección de productos a buen precio.\n3. Dixie. Precios bajos y productos raros, pero la calidad del Servicio puede estar lejos de ser alta.\n\n<b>Marketplays</b>\n1. Avito. Una plataforma donde todos pueden colocar un anuncio para vender algo, proporcionar diferentes servicios y vacantes para diferentes trabajos.\n2. Ozon/Wildberries. Tiendas en línea donde se pueden comprar diferentes productos, desde comida hasta instrumentos musicales. La entrega de los productos se realiza en los puntos de recogida, que están abiertos en casi todos los distritos.\n3. Aliexpress. Una gran variedad de productos que no se encuentran en ningún otro lugar. Sin embargo, hay un problema con los largos plazos de entrega y la falta de fiabilidad.',
	# прочие переводы
		'Блоки': 'Bloques',
		'Жаргонизмы':'Jergas',
		'Крылатые выражения':'Expresiones aladas',
		'Транспорт':'Transporte',
		'Общественный транспорт':'Transporte público',
	# Перевод картинок блоков 
		'https://i.postimg.cc/HxC0J12W/1.jpg': 'https://i.postimg.cc/NLygQwsN/channel-dec-32-2.jpg',
		'https://i.postimg.cc/t7shbLQD/3.jpg': 'https://i.postimg.cc/VJ0fLWsx/channel-dec-31.jpg',
		'https://i.postimg.cc/75TD9LmG/6.jpg': 'https://i.postimg.cc/7C34vWvq/channel-dec-34-2.jpg',
		'https://i.postimg.cc/18gxB9MT/5.jpg': 'https://i.postimg.cc/K3ZSDBsr/channel-dec-33-2.jpg',
		'https://i.postimg.cc/bssMYrG4/4.jpg': 'https://i.postimg.cc/k6qz7y8y/channel-dec-35-2.jpg',


		# общество 
		'Почему посторонний может спросить сигарету или зажигалку?':'¿Por qué un extraño puede pedir un cigarrillo o un encendedor?',																											
		'Почему русские угрюмые?':'¿Por qué los rusos son malhumorados?',
		'Кто такой гопник?':'¿Quién es Gopnik?',
		'Кто такие маргиналы и где их можно встретить?':'¿Quiénes son los marginados y dónde se pueden encontrar?',
		'Почему люди собираются у подъезда?':'¿Por qué la gente se reúne en la entrada?',
		'Кто такие алкаши, пьянь?':'¿Quiénes son los borrachos?',
		'На какие части делится Москва?':'¿En qué partes se divide Moscú?',
		'Как принято говорить между собой у русских, присутствует ли у них жестикуляция, как они обращаются друг к другу?':'Como es costumbre hablar entre los rusos, ¿tienen gesticulación, cómo se dirigen el uno al otro?',
		'Как здороваются русские?':'¿Cómo saludan los rusos?',
		'Как в России относятся к женщинам?':'¿Cómo tratan a las mujeres en Rusia?',
		'Как в России относятся к мужчинам?':'¿Cómo tratan a los hombres en Rusia?',
		'Как прощаются русские?':'¿Cómo se despiden los rusos?',
		'Как в России относятся к ЛГБТ?':'¿Cómo son las personas LGBT en Rusia?',


		#общество ответы
		'Лучше выполнить его просьбу, если у вас действительно есть сигарета или зажигалка или все вместе. Это обычная просьба и в ней нет скрытого смысла. Человек обязательно поблагодарит вас за то что вы с ним и оставит вас в покое. Однако следует обращать внимание на внешний вид оппонента: если он опрятный и трезвый не бойтесь поделиться. Но начинать с этого момента диалог не принято. Если перед вами пьяный неопрятный человек, лучше сказать, что у вас нет ни сигареты ни зажигалки, и извиниться. Тогда человек отстанет от вас.':'Es mejor cumplir con su solicitud si realmente tiene un cigarrillo o un encendedor o todos juntos. Esta es una solicitud común y no tiene un significado oculto. La persona seguramente te agradecerá por estar con él y te dejará en paz. Sin embargo, debe prestar atención a la apariencia del oponente: si está ordenado y sobrio, no tenga miedo de compartir. Pero no se acepta iniciar un diálogo a partir de ese momento. Si estás frente a una persona borracha y descuidada, es mejor decir que no tienes un cigarrillo ni un encendedor y disculparte. Entonces el hombre te dejará atrás. ',
		'Русские не любят улыбаться без уважительной причины. Более того, в России любого, кто постоянно вежливо улыбается, считают неискренним, скрытным человеком, который отказывается показывать свои истинные чувства.':
			'A los rusos no les gusta sonreír sin una buena razón. Además, en Rusia, cualquiera que sonríe cortésmente constantemente se considera una persona falsa y secreta que se niega a Mostrar sus verdaderos sentimientos.',
		'Люди, ведущие разгульный образ жизни. Их можно определить по характерному внешнему виду: это спортивный костюм (Adidas, Puma, Nike), кепка на голове и немного неадекватнык вид. От них лучше держаться подальше, так как они могут быть вспыльчивы и наглы.':
			'Personas que llevan un estilo de vida desenfrenado. Se pueden identificar por su apariencia característica: este es un traje deportivo (Adidas, Puma, Nike), una gorra en la cabeza y un aspecto ligeramente inadecuado. Es mejor mantenerse alejado de ellos, ya que pueden ser de mal genio y descarados.',
		'У подъезда или в подъезде чаще всего, в метро, в темное время суток.':'En la entrada o en la entrada más a menudo, en el metro, en la oscuridad.',
		'В спальных районах Москвы принято собираться у подъезда человека, который организовал встречу. Таким образом, если нет определенной цели куда направиться и чем заняться, люди выясняют это на месте. У подъезда встречаются, потому что чаще всего, если люди живут рядом, то таким образом удобнее и понятнее удается пересечься.':
			'En las áreas para dormir de Moscú, es costumbre reunirse en la entrada de la persona que organizó la reunión. Por lo tanto, si no hay un objetivo definido a dónde ir y qué hacer, la gente lo descubre en el acto. En la entrada se encuentran, porque la mayoría de las veces, si las personas viven cerca, entonces es más conveniente y más claro para cruzar.',
		'Местная маргиналия. Тот самый стереотип за рубежом, расценивающий менталитет русских. Алкоголики, которые из самого дешёвого алкоголя выбирают водку или пиво.':
			'Marginalidad local. El mismo estereotipo en el extranjero que considera la mentalidad de los rusos. Los alcohólicos que eligen el vodka o la cerveza del alcohol más barato.',
		'Россия — страна с федеральной форомой административного деления. Москва — город федерального значения, который так же делится на субъекты, которые могут влиять на решения московской думы. Районы Москвы отличаются ценообразованием, архитектурой и даже культурой.':
			'Rusia es un país con una división administrativa Federal. Moscú es una ciudad de importancia Federal, que también se divide en sujetos que pueden influir en las decisiones de la Duma de Moscú. Los distritos de Moscú difieren en precios, arquitectura e incluso cultura.',
		'Изначально к незнакомому человеку принято обращаться на вы, далее, спустя продолжительность общения люди договариваются как им комфортнее, чтобы к ним обращались. Почти всегда далее люди переходят к обращению на ты. Русские: открытые люди, просто им требуется чуть больше одной встречи, чтобы раскрыться. Однако они готовы помочь любому нуждающемуся в помощи, если он об этом попросит.':
			'Inicialmente, se acepta que un extraño se dirija a usted, luego, después de la Duración de la comunicación, las personas acuerdan cómo se sienten más cómodas para ser contactadas. Casi siempre, la gente va más allá de la conversión a TI. Rusos: gente abierta, solo necesitan un poco más de una reunión para abrirse. Sin embargo, están dispuestos a ayudar a cualquier persona que lo necesite si lo solicita.',
		'Встретившись с приятелем в неформальной обстановке обмениваются улыбкой, здороваются в принятой манере(обычно это: Привет! Здорово!)пожимают руку, обнимаются.\nВ формальной обстановке русские одаривают сдержанной улыбкой в знак вежливости(но также зависит от их персонального настроения) и пожимают руку, предоставившись.':
			'Después de reunirse con un amigo en un ambiente informal, intercambian una sonrisa, saludan de una manera aceptada (por lo general: ¡hola! ¡Genial!) estrechan la mano, se abrazan.\nEn un entorno formal, los rusos regalan una sonrisa discreta en señal de cortesía(pero también depende de su estado de ánimo personal) y se dan la mano cuando se les concede.',
		'На равных, как и к мужчинам. В обществе с женщинами обращаются вежливо и уважительно: придерживают двери, уступают место.':'Igual que con los hombres. En la sociedad, las mujeres son tratadas educadamente y Respetuosamente: sujetan las puertas, dan paso.',
		'Уважительно и на равных, главное, соблюдать принятый образ поведения: строгий и сдержанный, но при этом брутальный, чтобы не возникало лишних вопросов.':'Respetuosamente y en igualdad de condiciones, lo principal es observar el comportamiento aceptado: estricto y discreto, pero al mismo tiempo brutal, para que no surjan preguntas innecesarias.',
		'На прощание русские говорят "Досвидания!". Смысл слова заключается в том, что прощающиеся надеятся на встречи в дальнейшем. Они желают удачи и искренне желают встретиться еще.':'En la despedida, los rusos dicen " ¡dos Testigos!". El significado de la palabra es que los despedidos esperan reuniones en el futuro. Desean buena suerte y sinceramente desean reunirse más.',
		'В обществе отношение довольно нейтрально. Официально:\n30 ноября 2023 года судья Верховного суда РФ Олег Нефёдов объявил «экстремистской организацией» и запретил «международное общественное движение ЛГБТ».':'En la sociedad la actitud es bastante neutral. Oficialmente:\nEl 30 de noviembre de 2023, el juez del Tribunal Supremo de la Federación rusa, Oleg Nefedov, declaró una "organización extremista" y prohibió el "movimiento social internacional LGBT".',


		'<b>🚗Исходя из общего рейтинга исследования, тремя лучшими приложениями каршеринга признаны:</b>\n1. BelkaCar\n2. "Карусель"\n3. Anytime\n\n<b>🚕Для вызова такси отлично подходят:</b>\n1. ЯндексGo\n2. СитиМобил\n3. Uber':
			'<b>🚗Según la clasificación general del estudio, se reconocen las tres mejores aplicaciones de CarShare:</b>\n1. BelkaCar\n2. "Карусель"\n3. Anytime\n\n<b>🚕Para llamar a un taxi son excelentes:</b>\n1. ЯндексGo\n2. СитиМобил\n3. Uber',
		'<b>Крылатые выражения</b>\n\n1. "Ни пуха, ни пера" - выражение, пожелание удачи.\n2. "Хоть кол на голове теши" - про очень упрямого человека.\n3. "Как с гуся вода" - о чем-то очень легком.\n4. "Умом Россию не понять" - о том, что Россия загадочная и сложная страна.\n5. "Пошел в ноль" - описывает событие, которое не оправдало ожиданий.\n6. "Не бояться волка, а бояться бабушку" - о неожиданном источнике проблем или опасности.\n7. "Бить баклуши" - означает надуться, делать вид, что чего-то не знаешь.\n8. "Дуракам закон не писан" - о том, что глупые люди могут делать что угодно.\n9. "Муха медовая" - о том, что что-то приятное и легкое.\n10. "Не пойми не примите" - выражение раздражения или удивления.\n11. "Ботинки на выброс" (значит, выгнать кого-то из партии или коллектива)\n12. "Стеклянные души" (люди, чувства которых очень хрупки)\n13. "Кустарник на печи" (непонятный, заумный разговор)\n14. "Рубаха на вырост" (как временное средство устранения недостатка)\n15. "Разбил животом" (проиграл, потерпел неудачу)\n16. "Дубиной мерить" (устрашать, давить силой)\n17. "Крокодил слёз не проливает" (о бесчувственности, равнодушии)\n18. "Солнце-сковорода" (очень жарко)\n19. "Маски шатки" (ложь, обман)\n20. "Поедет в коляске" (получит по заслугам)':
		 '<b>Expresiones aladas</b>\n\n1. "Ni pelusa, ni pluma" - es una expresión, un deseo de buena suerte.\n2. "Al menos una estaca en la cabeza de tesha" - es sobre una persona muy obstinada.\n3. "Como el agua de un ganso" - sobre algo muy fácil.\n4. "La mente no entiende a Rusia" - que Rusia es un país misterioso y complejo.\n5. "Se fue a cero" - describe un evento que no cumplió con las expectativas.\n6. "No temer al lobo, sino temer a la abuela" - sobre una fuente inesperada de problemas o peligro.\n7. "Patear los Pulgares" - significa exagerar, fingir que no sabes algo.\n8. "La ley no está escrita para los tontos" - que las personas estúpidas pueden hacer cualquier cosa.\n9. "La mosca de la miel" - sobre el hecho de que algo agradable y fácil.\n10. "No comprendas no aceptes" - es una expresión de irritación o sorpresa.\n11. "Botas de expulsión" - (significa expulsar a alguien de un partido o equipo)\n12. "Almas de cristal" - (personas cuyos sentimientos son muy frágiles)\n13. "Arbusto en el horno " - (conversación incomprensible y aberrante)\n14. "Camisa para el crecimiento" - (como un remedio temporal para la deficiencia)\n15. "Aplastado por el estómago" - (perdido, fallado)\n16. "Medir porras" - (asustar, presionar por la fuerza)\n17. "El cocodrilo no derrama lágrimas" - (sobre la insensibilidad, la indiferencia)\n18. "Sol-sartén" - (muy caliente)\n19. "Máscaras shatka" - (mentira, engaño)\n20. "Va en silla de ruedas" - (recibirá lo que merece)',
		'<b>Жаргонизмы</b>\n\n1. Мыло — электронная почта\nБаранка, бублик — руль\n2. Дирик — директор\n3. Фраер — напоказ модно одетый человек, наивный человек\n3. Кент — приятель, товарищ\n4. Мани, кеш, бабки — деньги\n5. Тачка — машина\n6. Пиар — способы продвижения и получения популярности в обществе\n7. Хайп — кратковременная популярность':
			'<b>Jergas</b>\n\n1. Mylo (jabón) — correo electrónico\n2. Baranka, bublik (carnero, bagel) — volante\n3. Dirik — director\n4. Fryer — hombre vestido de moda, hombre ingenuo\n5. Kent — amigo, compañero\n6. Mani, caché, babki (abuelas) - dinero\n7. Tachka (caretilla) — coche, carro\n8. Hayp — popularidad a corto plazo'
	}	
}
	



# -------------------------------------------------------------------------------
# ПЕРЕВОД ТЕКСТА
# -------------------------------------------------------------------------------
def ll(text,lang='ru'):
	if lang == 'ru':
		return text
	else:
		global trans
		try:
			return trans[lang][text]
		except:
			return text